//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class Color_Interop : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Color_Interop(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Color_Interop obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Color_Interop obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~Color_Interop() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ConvPINVOKE.delete_Color_Interop(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public double R {
    set {
      ConvPINVOKE.Color_Interop_R_set(swigCPtr, value);
    } 
    get {
      double ret = ConvPINVOKE.Color_Interop_R_get(swigCPtr);
      return ret;
    } 
  }

  public double G {
    set {
      ConvPINVOKE.Color_Interop_G_set(swigCPtr, value);
    } 
    get {
      double ret = ConvPINVOKE.Color_Interop_G_get(swigCPtr);
      return ret;
    } 
  }

  public double B {
    set {
      ConvPINVOKE.Color_Interop_B_set(swigCPtr, value);
    } 
    get {
      double ret = ConvPINVOKE.Color_Interop_B_get(swigCPtr);
      return ret;
    } 
  }

  public double A {
    set {
      ConvPINVOKE.Color_Interop_A_set(swigCPtr, value);
    } 
    get {
      double ret = ConvPINVOKE.Color_Interop_A_get(swigCPtr);
      return ret;
    } 
  }

  public Color_Interop() : this(ConvPINVOKE.new_Color_Interop(), true) {
  }

}
