//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class MapBackground_Interop : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal MapBackground_Interop(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(MapBackground_Interop obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(MapBackground_Interop obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~MapBackground_Interop() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ConvPINVOKE.delete_MapBackground_Interop(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public bool highQuality {
    set {
      ConvPINVOKE.MapBackground_Interop_highQuality_set(swigCPtr, value);
    } 
    get {
      bool ret = ConvPINVOKE.MapBackground_Interop_highQuality_get(swigCPtr);
      return ret;
    } 
  }

  public bool clipToBounds {
    set {
      ConvPINVOKE.MapBackground_Interop_clipToBounds_set(swigCPtr, value);
    } 
    get {
      bool ret = ConvPINVOKE.MapBackground_Interop_clipToBounds_get(swigCPtr);
      return ret;
    } 
  }

  public double minValue {
    set {
      ConvPINVOKE.MapBackground_Interop_minValue_set(swigCPtr, value);
    } 
    get {
      double ret = ConvPINVOKE.MapBackground_Interop_minValue_get(swigCPtr);
      return ret;
    } 
  }

  public double maxValue {
    set {
      ConvPINVOKE.MapBackground_Interop_maxValue_set(swigCPtr, value);
    } 
    get {
      double ret = ConvPINVOKE.MapBackground_Interop_maxValue_get(swigCPtr);
      return ret;
    } 
  }

  public int matrix {
    set {
      ConvPINVOKE.MapBackground_Interop_matrix_set(swigCPtr, value);
    } 
    get {
      int ret = ConvPINVOKE.MapBackground_Interop_matrix_get(swigCPtr);
      return ret;
    } 
  }

  public Color_Interop min_color {
    set {
      ConvPINVOKE.MapBackground_Interop_min_color_set(swigCPtr, Color_Interop.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ConvPINVOKE.MapBackground_Interop_min_color_get(swigCPtr);
      Color_Interop ret = (cPtr == global::System.IntPtr.Zero) ? null : new Color_Interop(cPtr, false);
      return ret;
    } 
  }

  public Color_Interop max_color {
    set {
      ConvPINVOKE.MapBackground_Interop_max_color_set(swigCPtr, Color_Interop.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ConvPINVOKE.MapBackground_Interop_max_color_get(swigCPtr);
      Color_Interop ret = (cPtr == global::System.IntPtr.Zero) ? null : new Color_Interop(cPtr, false);
      return ret;
    } 
  }

  public static vector_colors GetMatrix(double Left, double Top, double Right, double Bottom, int numColumns, int numRows, vector_background backgrounds) {
    vector_colors ret = new vector_colors(ConvPINVOKE.MapBackground_Interop_GetMatrix(Left, Top, Right, Bottom, numColumns, numRows, vector_background.getCPtr(backgrounds)), true);
    if (ConvPINVOKE.SWIGPendingException.Pending) throw ConvPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public MapBackground_Interop() : this(ConvPINVOKE.new_MapBackground_Interop(), true) {
  }

}
