//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class MapLayer_Interop : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal MapLayer_Interop(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(MapLayer_Interop obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(MapLayer_Interop obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~MapLayer_Interop() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ConvPINVOKE.delete_MapLayer_Interop(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public map_int_polygon polygons {
    set {
      ConvPINVOKE.MapLayer_Interop_polygons_set(swigCPtr, map_int_polygon.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ConvPINVOKE.MapLayer_Interop_polygons_get(swigCPtr);
      map_int_polygon ret = (cPtr == global::System.IntPtr.Zero) ? null : new map_int_polygon(cPtr, false);
      return ret;
    } 
  }

  public map_int_polyline polylines {
    set {
      ConvPINVOKE.MapLayer_Interop_polylines_set(swigCPtr, map_int_polyline.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ConvPINVOKE.MapLayer_Interop_polylines_get(swigCPtr);
      map_int_polyline ret = (cPtr == global::System.IntPtr.Zero) ? null : new map_int_polyline(cPtr, false);
      return ret;
    } 
  }

  public map_int_icon icons {
    set {
      ConvPINVOKE.MapLayer_Interop_icons_set(swigCPtr, map_int_icon.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ConvPINVOKE.MapLayer_Interop_icons_get(swigCPtr);
      map_int_icon ret = (cPtr == global::System.IntPtr.Zero) ? null : new map_int_icon(cPtr, false);
      return ret;
    } 
  }

  public MapLayer_Interop() : this(ConvPINVOKE.new_MapLayer_Interop(), true) {
  }

}
