//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class MapPolygon_Interop : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal MapPolygon_Interop(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(MapPolygon_Interop obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(MapPolygon_Interop obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~MapPolygon_Interop() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ConvPINVOKE.delete_MapPolygon_Interop(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public Color_Interop color {
    set {
      ConvPINVOKE.MapPolygon_Interop_color_set(swigCPtr, Color_Interop.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ConvPINVOKE.MapPolygon_Interop_color_get(swigCPtr);
      Color_Interop ret = (cPtr == global::System.IntPtr.Zero) ? null : new Color_Interop(cPtr, false);
      return ret;
    } 
  }

  public double thickness {
    set {
      ConvPINVOKE.MapPolygon_Interop_thickness_set(swigCPtr, value);
    } 
    get {
      double ret = ConvPINVOKE.MapPolygon_Interop_thickness_get(swigCPtr);
      return ret;
    } 
  }

  public bool dashed {
    set {
      ConvPINVOKE.MapPolygon_Interop_dashed_set(swigCPtr, value);
    } 
    get {
      bool ret = ConvPINVOKE.MapPolygon_Interop_dashed_get(swigCPtr);
      return ret;
    } 
  }

  public vector_pair_double_double coordinates {
    set {
      ConvPINVOKE.MapPolygon_Interop_coordinates_set(swigCPtr, vector_pair_double_double.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ConvPINVOKE.MapPolygon_Interop_coordinates_get(swigCPtr);
      vector_pair_double_double ret = (cPtr == global::System.IntPtr.Zero) ? null : new vector_pair_double_double(cPtr, false);
      return ret;
    } 
  }

  public MapPolygon_Interop() : this(ConvPINVOKE.new_MapPolygon_Interop(), true) {
  }

}
