//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class pair_timeseries : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal pair_timeseries(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(pair_timeseries obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(pair_timeseries obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~pair_timeseries() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ConvPINVOKE.delete_pair_timeseries(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public pair_timeseries() : this(ConvPINVOKE.new_pair_timeseries__SWIG_0(), true) {
  }

  public pair_timeseries(cweeDateTime t1, float t2) : this(ConvPINVOKE.new_pair_timeseries__SWIG_1(cweeDateTime.getCPtr(t1), t2), true) {
    if (ConvPINVOKE.SWIGPendingException.Pending) throw ConvPINVOKE.SWIGPendingException.Retrieve();
  }

  public pair_timeseries(cweeDateTime t1, SWIGTYPE_p_float t2) : this(ConvPINVOKE.new_pair_timeseries__SWIG_2(cweeDateTime.swigRelease(t1), SWIGTYPE_p_float.swigRelease(t2)), true) {
    if (ConvPINVOKE.SWIGPendingException.Pending) throw ConvPINVOKE.SWIGPendingException.Retrieve();
  }

  public pair_timeseries(SWIGTYPE_p_std__pairT_cweeDateTime_float_t t) : this(ConvPINVOKE.new_pair_timeseries__SWIG_3(SWIGTYPE_p_std__pairT_cweeDateTime_float_t.getCPtr(t)), true) {
    if (ConvPINVOKE.SWIGPendingException.Pending) throw ConvPINVOKE.SWIGPendingException.Retrieve();
  }

  public cweeDateTime first {
    set {
      ConvPINVOKE.pair_timeseries_first_set(swigCPtr, cweeDateTime.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ConvPINVOKE.pair_timeseries_first_get(swigCPtr);
      cweeDateTime ret = (cPtr == global::System.IntPtr.Zero) ? null : new cweeDateTime(cPtr, false);
      return ret;
    } 
  }

  public float second {
    set {
      ConvPINVOKE.pair_timeseries_second_set(swigCPtr, value);
    } 
    get {
      float ret = ConvPINVOKE.pair_timeseries_second_get(swigCPtr);
      return ret;
    } 
  }

}
