//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class pair_int_pair_string_vector_string : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal pair_int_pair_string_vector_string(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(pair_int_pair_string_vector_string obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(pair_int_pair_string_vector_string obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~pair_int_pair_string_vector_string() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ConvPINVOKE.delete_pair_int_pair_string_vector_string(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public pair_int_pair_string_vector_string() : this(ConvPINVOKE.new_pair_int_pair_string_vector_string__SWIG_0(), true) {
  }

  public pair_int_pair_string_vector_string(int t1, pair_string_vector_string t2) : this(ConvPINVOKE.new_pair_int_pair_string_vector_string__SWIG_1(t1, pair_string_vector_string.getCPtr(t2)), true) {
    if (ConvPINVOKE.SWIGPendingException.Pending) throw ConvPINVOKE.SWIGPendingException.Retrieve();
  }

  public pair_int_pair_string_vector_string(SWIGTYPE_p_int t1, pair_string_vector_string t2) : this(ConvPINVOKE.new_pair_int_pair_string_vector_string__SWIG_2(SWIGTYPE_p_int.swigRelease(t1), pair_string_vector_string.swigRelease(t2)), true) {
    if (ConvPINVOKE.SWIGPendingException.Pending) throw ConvPINVOKE.SWIGPendingException.Retrieve();
  }

  public pair_int_pair_string_vector_string(SWIGTYPE_p_std__pairT_int_PairT_std__string_std__vectorT_std__string_t_t_t t) : this(ConvPINVOKE.new_pair_int_pair_string_vector_string__SWIG_3(SWIGTYPE_p_std__pairT_int_PairT_std__string_std__vectorT_std__string_t_t_t.getCPtr(t)), true) {
    if (ConvPINVOKE.SWIGPendingException.Pending) throw ConvPINVOKE.SWIGPendingException.Retrieve();
  }

  public int first {
    set {
      ConvPINVOKE.pair_int_pair_string_vector_string_first_set(swigCPtr, value);
    } 
    get {
      int ret = ConvPINVOKE.pair_int_pair_string_vector_string_first_get(swigCPtr);
      return ret;
    } 
  }

  public pair_string_vector_string second {
    set {
      ConvPINVOKE.pair_int_pair_string_vector_string_second_set(swigCPtr, pair_string_vector_string.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ConvPINVOKE.pair_int_pair_string_vector_string_second_get(swigCPtr);
      pair_string_vector_string ret = (cPtr == global::System.IntPtr.Zero) ? null : new pair_string_vector_string(cPtr, false);
      return ret;
    } 
  }

}
