//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class pair_double_double : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal pair_double_double(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(pair_double_double obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(pair_double_double obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~pair_double_double() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ConvPINVOKE.delete_pair_double_double(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public pair_double_double() : this(ConvPINVOKE.new_pair_double_double__SWIG_0(), true) {
  }

  public pair_double_double(double t1, double t2) : this(ConvPINVOKE.new_pair_double_double__SWIG_1(t1, t2), true) {
  }

  public pair_double_double(SWIGTYPE_p_double t1, SWIGTYPE_p_double t2) : this(ConvPINVOKE.new_pair_double_double__SWIG_2(SWIGTYPE_p_double.swigRelease(t1), SWIGTYPE_p_double.swigRelease(t2)), true) {
    if (ConvPINVOKE.SWIGPendingException.Pending) throw ConvPINVOKE.SWIGPendingException.Retrieve();
  }

  public pair_double_double(SWIGTYPE_p_std__pairT_double_double_t t) : this(ConvPINVOKE.new_pair_double_double__SWIG_3(SWIGTYPE_p_std__pairT_double_double_t.getCPtr(t)), true) {
    if (ConvPINVOKE.SWIGPendingException.Pending) throw ConvPINVOKE.SWIGPendingException.Retrieve();
  }

  public double first {
    set {
      ConvPINVOKE.pair_double_double_first_set(swigCPtr, value);
    } 
    get {
      double ret = ConvPINVOKE.pair_double_double_first_get(swigCPtr);
      return ret;
    } 
  }

  public double second {
    set {
      ConvPINVOKE.pair_double_double_second_set(swigCPtr, value);
    } 
    get {
      double ret = ConvPINVOKE.pair_double_double_second_get(swigCPtr);
      return ret;
    } 
  }

}
