//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class ScriptingNode : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ScriptingNode(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ScriptingNode obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(ScriptingNode obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~ScriptingNode() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ConvPINVOKE.delete_ScriptingNode(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public ScriptingNode() : this(ConvPINVOKE.new_ScriptingNode(), true) {
  }

  public string text {
    set {
      ConvPINVOKE.ScriptingNode_text_set(swigCPtr, value);
      if (ConvPINVOKE.SWIGPendingException.Pending) throw ConvPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = ConvPINVOKE.ScriptingNode_text_get(swigCPtr);
      if (ConvPINVOKE.SWIGPendingException.Pending) throw ConvPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public int startLine {
    set {
      ConvPINVOKE.ScriptingNode_startLine_set(swigCPtr, value);
    } 
    get {
      int ret = ConvPINVOKE.ScriptingNode_startLine_get(swigCPtr);
      return ret;
    } 
  }

  public int startColumn {
    set {
      ConvPINVOKE.ScriptingNode_startColumn_set(swigCPtr, value);
    } 
    get {
      int ret = ConvPINVOKE.ScriptingNode_startColumn_get(swigCPtr);
      return ret;
    } 
  }

  public int endLine {
    set {
      ConvPINVOKE.ScriptingNode_endLine_set(swigCPtr, value);
    } 
    get {
      int ret = ConvPINVOKE.ScriptingNode_endLine_get(swigCPtr);
      return ret;
    } 
  }

  public int endColumn {
    set {
      ConvPINVOKE.ScriptingNode_endColumn_set(swigCPtr, value);
    } 
    get {
      int ret = ConvPINVOKE.ScriptingNode_endColumn_get(swigCPtr);
      return ret;
    } 
  }

  public WaterWatchEnums.ScriptNodeType type {
    set {
      ConvPINVOKE.ScriptingNode_type_set(swigCPtr, (int)value);
    } 
    get {
      WaterWatchEnums.ScriptNodeType ret = (WaterWatchEnums.ScriptNodeType)ConvPINVOKE.ScriptingNode_type_get(swigCPtr);
      return ret;
    } 
  }

  public string typeHint {
    set {
      ConvPINVOKE.ScriptingNode_typeHint_set(swigCPtr, value);
      if (ConvPINVOKE.SWIGPendingException.Pending) throw ConvPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = ConvPINVOKE.ScriptingNode_typeHint_get(swigCPtr);
      if (ConvPINVOKE.SWIGPendingException.Pending) throw ConvPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public int depth {
    set {
      ConvPINVOKE.ScriptingNode_depth_set(swigCPtr, value);
    } 
    get {
      int ret = ConvPINVOKE.ScriptingNode_depth_get(swigCPtr);
      return ret;
    } 
  }

}
