//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class ScriptingNode : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ScriptingNode(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ScriptingNode obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(ScriptingNode obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~ScriptingNode() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ConvPINVOKE.delete_ScriptingNode(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public ScriptingNode() : this(ConvPINVOKE.new_ScriptingNode(), true) {
  }

  public string text_get() {
    string ret = ConvPINVOKE.ScriptingNode_text_get(swigCPtr);
    return ret;
  }

  public int startLine_get() {
    int ret = ConvPINVOKE.ScriptingNode_startLine_get(swigCPtr);
    return ret;
  }

  public int startColumn_get() {
    int ret = ConvPINVOKE.ScriptingNode_startColumn_get(swigCPtr);
    return ret;
  }

  public int endLine_get() {
    int ret = ConvPINVOKE.ScriptingNode_endLine_get(swigCPtr);
    return ret;
  }

  public int endColumn_get() {
    int ret = ConvPINVOKE.ScriptingNode_endColumn_get(swigCPtr);
    return ret;
  }

  public WaterWatchEnums.ScriptNodeType type_get() {
    WaterWatchEnums.ScriptNodeType ret = (WaterWatchEnums.ScriptNodeType)ConvPINVOKE.ScriptingNode_type_get(swigCPtr);
    return ret;
  }

  public string typeHint_get() {
    string ret = ConvPINVOKE.ScriptingNode_typeHint_get(swigCPtr);
    return ret;
  }

  public int depth_get() {
    int ret = ConvPINVOKE.ScriptingNode_depth_get(swigCPtr);
    return ret;
  }

  public void text_set(string s) {
    ConvPINVOKE.ScriptingNode_text_set(swigCPtr, s);
    if (ConvPINVOKE.SWIGPendingException.Pending) throw ConvPINVOKE.SWIGPendingException.Retrieve();
  }

  public void startLine_set(int s) {
    ConvPINVOKE.ScriptingNode_startLine_set(swigCPtr, s);
  }

  public void startColumn_set(int s) {
    ConvPINVOKE.ScriptingNode_startColumn_set(swigCPtr, s);
  }

  public void endLine_set(int s) {
    ConvPINVOKE.ScriptingNode_endLine_set(swigCPtr, s);
  }

  public void endColumn_set(int s) {
    ConvPINVOKE.ScriptingNode_endColumn_set(swigCPtr, s);
  }

  public void type_set(WaterWatchEnums.ScriptNodeType s) {
    ConvPINVOKE.ScriptingNode_type_set(swigCPtr, (int)s);
  }

  public void typeHint_set(string s) {
    ConvPINVOKE.ScriptingNode_typeHint_set(swigCPtr, s);
    if (ConvPINVOKE.SWIGPendingException.Pending) throw ConvPINVOKE.SWIGPendingException.Retrieve();
  }

  public void depth_set(int s) {
    ConvPINVOKE.ScriptingNode_depth_set(swigCPtr, s);
  }

}
